/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root';
import { Route as LoginImport } from './routes/login';
import { Route as AuthImport } from './routes/_auth';
import { Route as AuthIndexImport } from './routes/_auth.index';
import { Route as AuthBoardImport } from './routes/_auth.board';
import { Route as AuthBoardBoardImport } from './routes/_auth.board.$board';

// Create/Update Routes

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute
} as any);

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute
} as any);

const AuthIndexRoute = AuthIndexImport.update({
  path: '/',
  getParentRoute: () => AuthRoute
} as any);

const AuthBoardRoute = AuthBoardImport.update({
  path: '/board',
  getParentRoute: () => AuthRoute
} as any);

const AuthBoardBoardRoute = AuthBoardBoardImport.update({
  path: '/$board',
  getParentRoute: () => AuthBoardRoute
} as any);

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth';
      path: '';
      fullPath: '';
      preLoaderRoute: typeof AuthImport;
      parentRoute: typeof rootRoute;
    };
    '/login': {
      id: '/login';
      path: '/login';
      fullPath: '/login';
      preLoaderRoute: typeof LoginImport;
      parentRoute: typeof rootRoute;
    };
    '/_auth/board': {
      id: '/_auth/board';
      path: '/board';
      fullPath: '/board';
      preLoaderRoute: typeof AuthBoardImport;
      parentRoute: typeof AuthImport;
    };
    '/_auth/': {
      id: '/_auth/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof AuthIndexImport;
      parentRoute: typeof AuthImport;
    };
    '/_auth/board/$board': {
      id: '/_auth/board/$board';
      path: '/$board';
      fullPath: '/board/$board';
      preLoaderRoute: typeof AuthBoardBoardImport;
      parentRoute: typeof AuthBoardImport;
    };
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  AuthRoute: AuthRoute.addChildren({
    AuthBoardRoute: AuthBoardRoute.addChildren({ AuthBoardBoardRoute }),
    AuthIndexRoute
  }),
  LoginRoute
});

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_auth",
        "/login"
      ]
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/board",
        "/_auth/"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/_auth/board": {
      "filePath": "_auth.board.tsx",
      "parent": "/_auth",
      "children": [
        "/_auth/board/$board"
      ]
    },
    "/_auth/": {
      "filePath": "_auth.index.tsx",
      "parent": "/_auth"
    },
    "/_auth/board/$board": {
      "filePath": "_auth.board.$board.tsx",
      "parent": "/_auth/board"
    }
  }
}
ROUTE_MANIFEST_END */
